monolog:
  handlers:
    main:
      type: stream
      path: '%kernel.logs_dir%/%kernel.environment%.log'
      level: debug
      channels: ['!event']
    console:
      type:   console
      level: info
      process_psr_3_messages: false
      channels: ['!event', '!doctrine']
      verbosity_levels:
        VERBOSITY_NORMAL: debug

