parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Kernel.php}'

    App\Frontend\:
        resource: '../src/Frontend'
        tags: ['controller.service_arguments']




